### ISSUE TITLE
Accept a sub-syntax so we can support scss, less, etc

### ISSUE THREAD

**Issue by 43081j** [43081j/postcss-js-core#1]
Currently, we do not actually support sass/less properly since they too are implemented as custom postcss syntaxes.

Since you can only have one syntax, it means we're now overriding the inner syntax.

Ideally, we'd support something like this in postcss' config files:

```json
{
  "syntax": "postcss-lit",
  "syntaxOptions": {
    "syntax": "postcss-less"
  }
}
```

though that would also mean we'd need stylelint to support the same, _or_ just tell stylelint users they _must_ have a postcss config file...

i think i'll need your help here @ai to figure this concept out.

ideally we want to avoid requiring consumers to **programmatically** call postcss just so they can specify the sub-syntax (e.g. LESS). 

one thought was that we could read the postcss config file (if one exists) and look for a `"syntaxOptions"` like above. though syntaxes are **synchronous** and loading postcssrc is **async**... meaning we wouldn't really be able to do it.

**Comment by 43081j** [comment]
once we get hold of the sub-syntax name, it should be super easy to pass it through when we call the parser under the hood.

we basically want to do the same logic as postcss-cli: load the config file, get hold of the imported `syntax` and call its `parse` function or fallback to postcss' own.


we should try come up with a standard way of achieving this so we don't end up with side effects/postcss api mutations/patches like we've seen in the past.

**Comment by ai** [comment]
> i think i'll need your help here @ai to figure this concept out.

Honestly, I think the task is too complicated and not really popular.

CSS evolving very fast and preprocessors have no solid future.

Standard CSS in CSS-in-JS is our main future.

**Comment by ai** [comment]
Adding syntax option will be hard (especially, because most tools has own PostCSS config loader).

I think the best API is to use separated files for imports `"syntax": "postcss-lit/less"`. Anyway, we have a very small amount of these inner syntaxes.

**Comment by 43081j** [comment]
> Standard CSS in CSS-in-JS is our main future

as a huge proponent of web standards/APIs i strongly agree with that... though we still have quite a lot of people/projects around using sass/less it seems.

> I think the best API is to use separated files for imports "syntax": "postcss-lit/less"

that is the easiest solution without having to change much i think.

it is a shame, though, as we would have to tie this generic package into understanding specific sub-syntaxes.

given that there's only two im aware of  still widely in use though (sass, less), maybe we will be fine.

postcss basically `import(config.syntax)` from what i understand. so i could just publish a `less.js` and a `scss.js` or some such thing in each css-in-js syntax.

**Comment by ai** [comment]
> it is a shame, though, as we would have to tie this generic package into understanding specific sub-syntaxes.

Agree. But it is not so big problem since we have only a small number of them: Sass, Less, SugarSS (maybe only Sass and Less).

**Comment by karlhorky** [comment]
Wonder if most subsyntax features will converge with vanilla CSS in the future, since vanilla CSS will support nesting (albeit with [a different syntax](https://webkit.org/blog/13607/help-choose-from-options-for-css-nesting-syntax/)).

Eg. if Emotion or Styled Components (or both) were to support this new nesting syntax instead of non-standards like Sass or Less (and Stylelint would also support this syntax), then maybe there could be less custom code in the customSyntax for this...

**Comment by 43081j** [comment]
i think so yeah

LESS already seems to be valid (parseable) CSS. SCSS not so much, but isn't far off.

ideally people will move towards vanilla css anyway over time since the same features are becoming available natively 🙏 

i'd highly recommend people try use postcss-styled-components _without_ the sub-syntax first, and if it works fine on their project, leave it.
